; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                              = 11220621-x86_64 macOS           
[ DataSettings ]
datatype                         = snProtein                       
MissingBaseSymbol                = ?                               
IdenticalBaseSymbol              = .                               
GapSymbol                        = -                               
Labelled Sites                   = All Sites                       
Labels to Include                =                                 
[ ProcessTypes ]
ppModelSelML                     = true                            
[ AnalysisSettings ]
Analysis                         = Model Selection (ML)            
Tree to Use                      = Automatic (Neighbor-joining tree)
User Tree File                   = Not Applicable                  
Statistical Method               = Maximum Likelihood              
Substitution Model               = ====================            
Substitutions Type               = Amino acid                      
Data Subset to Use               = ====================            
Gaps/Missing Data Treatment      = Partial deletion                
Site Coverage Cutoff (%)         = 90                              
Branch Swap Filter               = None                            
System Resource Usage            = ====================            
Number of Threads                = 30                              
Has Time Limit                   = False                           
Maximum Execution Time           = -1                              
